version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12341234
      MYSQL_DATABASE: spk_hipertensi_ci4_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: 12341234
    volumes:
      - ./data:/var/lib/mysql
